SELECT * FROM CUSTOMERS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM STORES;
SELECT * FROM PRODUCTS;


-- Q1
SELECT O.ORDER_ID, O.ORDER_DATETIME
FROM ORDERS O
LEFT JOIN CUSTOMERS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
ORDER BY ORDER_DATETIME	DESC
FETCH FIRST 1 ROWS ONLY;

-- Q2
SELECT COUNT(*) FROM ORDERS;

--Q3
DESCRIBE STORES;

--Q4
SELECT * FROM ORDER_ITEMS
WHERE UNIT_PRICE=(
SELECT MAX("UNIT_PRICE")
FROM ORDER_ITEMS);

--Q5
SELECT COUNT(*),ORDER_STATUS FROM ORDERS
GROUP BY ORDER_STATUS;


--Q6
SELECT TO_CHAR(ORDER_DATETIME,'MON'), COUNT(*) FROM ORDERS
WHERE ORDER_STATUS='COMPLETE'
GROUP BY TO_CHAR(ORDER_DATETIME,'MON')
ORDER BY COUNT(*) DESC
FETCH FIRST 1 ROWS ONLY;

---Q7
SELECT COUNT(*),STORE_ID FROM(SELECT O.STORE_ID,O.ORDER_STATUS
FROM ORDERS O
LEFT JOIN STORES S
ON O.STORE_ID=S.STORE_ID
WHERE O.ORDER_STATUS='COMPLETE')
GROUP BY STORE_ID
ORDER BY COUNT(*) DESC
FETCH FIRST 1 ROWS ONLY;



--Q8
SELECT TO_CHAR(ORDER_DATETIME,'MON/YYYY'), SUM(QUANTITY*UNIT_PRICE), ORDER_STATUS
FROM(SELECT I.ORDER_ID, I.UNIT_PRICE, I.QUANTITY, O.ORDER_STATUS,O.ORDER_DATETIME
FROM ORDER_ITEMS I
LEFT JOIN ORDERS O
ON I.ORDER_ID = O.ORDER_ID)
WHERE ORDER_STATUS='COMPLETE'
GROUP BY TO_CHAR(ORDER_DATETIME,'MON/YYYY'), ORDER_STATUS
ORDER BY SUM(QUANTITY*UNIT_PRICE) DESC
FETCH FIRST 1 ROWS ONLY;

--Q9
SELECT SUM(QUANTITY),PRODUCT_NAME FROM(
SELECT O.ORDER_ID, O.ORDER_STATUS, I.PRODUCT_ID, I.QUANTITY,P.PRODUCT_NAME	
FROM ORDER_ITEMS I
INNER JOIN ORDERS O
ON O.ORDER_ID=I.ORDER_ID
INNER JOIN PRODUCTS P
ON I.PRODUCT_ID	=P.PRODUCT_ID
WHERE ORDER_STATUS='COMPLETE')
GROUP BY PRODUCT_NAME
ORDER BY SUM(QUANTITY) DESC
FETCH FIRST 1 ROWS ONLY;




